"""Constants for neviweb component."""

DOMAIN = "neviweb"
CONF_NETWORK = 'network'
CONF_NETWORK2 = 'network2'

ATTR_SIGNATURE = "signature"
ATTR_POWER_MODE = "powerMode"
ATTR_INTENSITY = "intensity"
ATTR_RSSI = "rssi"
ATTR_WATTAGE = "wattage"
ATTR_WATTAGE_INSTANT = "wattageInstant"
ATTR_WATTAGE_OVERRIDE = "wattageOverride"
ATTR_SETPOINT_MODE = "setpointMode"
ATTR_ROOM_SETPOINT = "roomSetpoint"
ATTR_ROOM_TEMPERATURE = "roomTemperature"
ATTR_OUTPUT_PERCENT_DISPLAY = "outputPercentDisplay"
ATTR_ROOM_SETPOINT_MIN = "roomSetpointMin"
ATTR_ROOM_SETPOINT_MAX = "roomSetpointMax"
ATTR_OCCUPANCY = "occupancyMode"
ATTR_ALARM = "alarmsActive0"
ATTR_AWAY_SETPOINT = 'roomSetpointAway'
ATTR_EARLY_START = "earlyStart"
ATTR_LED_OFF = "statusLedOff" #intensity,red,green,blue
ATTR_LED_ON = "statusLedOn"
ATTR_KEYPAD = "lockKeypad"
ATTR_AWAY_MODE = "awayMode" #action
ATTR_TIMER = "powerTimer"
ATTR_MIN_INTENSITY = "intensityMin"
ATTR_EARLY_START = "earlyStart"
ATTR_DISPLAY_2 = "secondaryDisplay"
ATTR_TEMP_FORMAT = "temperatureFormat"
ATTR_STATE = "state"
ATTR_RED = "red"
ATTR_GREEN = "green"
ATTR_BLUE = "blue"
ATTR_ALERT_LOW = "alertLowAirTemp"
ATTR_BACKLIGHT = "backlightIntensityIdle"

MODE_AUTO = "auto"
MODE_AUTO_BYPASS = "autoBypass"
MODE_MANUAL = "manual"
MODE_AWAY = "away"
MODE_OFF = "off"
MODE_HOME = "home"

SERVICE_SET_LED_INDICATOR = "set_led_indicator"
SERVICE_SET_KEYPAD_LOCK = "set_keypad_lock"
SERVICE_SET_TIMER = "set_timer"
SERVICE_SET_SECOND_DISPLAY = "set_second_display"
SERVICE_SET_BACKLIGHT_IDLE = "set_backlight_idle"
