set_climate_keypad_lock:
  description: Lock or unlock climate device keypad.
  fields:
    entity_id:
      description: Name(s) of neviweb climate device to lock/unlock the keypad.
      example: "climate.neviweb_climate_office"
    lockKeypad:
      description: Device keypad status to set «locked» = Locked, «unlocked» = Unlocked.
      example: "locked"

set_light_keypad_lock:
  description: Lock or unlock light and dimmer device keypad.
  fields:
    entity_id:
      description: Name(s) of neviweb device to lock/unlock the keypad.
      example: "light.neviweb_light_office"
    lockKeypad:
      description: Device keypad status to set «locked» = Locked, «unlocked» = Unlocked.
      example: "locked"

set_switch_keypad_lock:
  description: Lock or unlock switch device keypad.
  fields:
    entity_id:
      description: Name(s) of neviweb device to lock/unlock the keypad.
      example: "switch.neviweb_switch_office"
    lockKeypad:
      description: Device keypad status to set «locked» = Locked, «unlocked» = Unlocked.
      example: "locked"

set_light_timer:
  description: Set light device timer, 0 = off, 1 to 10800 seconds = timer length. Devices will turn_off after that delay.
  fields:
    entity_id:
      description: Name(s) of neviweb light device to set the timer (light and dimmer).
      example: "light.neviweb_light_office"
    powerTimer:
      description: Time to set, 0 = no timer, 1 to 10800 = timer length in seconds.
      example: 60

set_switch_timer:
  description: Set device timer, 0 = off, 1 to 10800 seconds = timer length. Devices will turn_off after that delay.
  fields:
    entity_id:
      description: Name(s) of neviweb switch device to set the timer.
      example: "switch.neviweb_switch_office"
    powerTimer:
      description: Time to set, 0 = no timer, 1 to 10800 = timer length in seconds.
      example: 60

set_time_format:
  description: Set climate device time format 12h or 24h.
  fields:
    entity_id:
      description: Name(s) of neviweb device to set time format.
      example: "climate.neviweb_climate_office"
    timeFormat:
      description: Time format to set, 12  or 24.
      example: 24

set_temperature_format:
  description: Set climate device temperature format, celsius or fahrenheit.
  fields:
    entity_id:
      description: Name(s) of neviweb device to set temperature format.
      example: "climate.neviweb_climate_office"
    temperatureFormat:
      description: Temperature format to set, «celsius» or «fahrenheit».
      example: "celsius"

set_early_start:
  description: Set climate device heating early start on/off.
  fields:
    entity_id:
      description: Name(s) of neviweb device to set early start.
      example: "climate.neviweb_climate_office"
    earlyStart:
      description: «on» or «off», earlyStart status to set on/off.
      example: "on"

set_led_indicator:
  description: Set led indicator intensity an color, for each light state, on/off.
  fields:
    entity_id:
      description: Name(s) of neviweb light device to set the led color and intensity.
      example: "light.neviweb_light_office"
    state:
      description: 0 = when light is «off», 1 = when light is «on»
      example: 1
    intensity:
      description: 0 = off, 1 to 100 intensity.
      example: 50
    red:
      description: 0 to 255 RGB reb color indice.
      example: 25
    green:
      description: 0 to 255 RGB green color indice.
      example: 25
    blue:
      description: 0 to 255 RGB blue color indice.
      example: 255

set_second_display:
  description: Set the second thermostat display to show setpoint or outside temperature.
  fields:
    entity_id:
      description: Name(s) of device to set the second display.
      example: "climate.neviweb_climate_office"
    secondaryDisplay:
      description: «outsideTemperature» = outside temperature display, «default» = setpoint display.
      example: "outsideTemperature"

set_backlight:
  description: Set backlight intensity when idle, 0 = off when idle , on when active, 100 = always on.
  fields:
    entity_id:
      description: Name(s) of device to set the second display.
      example: "climate.neviweb_climate_office"
    backlightIntensityIdle:
      description: 0 = off when idle, 100 always on.
      example: 100

set_wattage:
  description: Set device wattageOverride value for light 0-1800w, and dimmer 0-600w.
  fields:
    entity_id:
      description: Name(s) of neviweb device to set the wattageOverride (light or dimmer).
      example: "light.neviweb_light_office"
    wattageOverride:
      description: wattage to set, 0-1800w light, 0-600w dimmer.
      example: 250

set_setpoint_max:
  description: Set climate device room setpoint max temperature.
  fields:
    entity_id:
      description: Name(s) of neviweb device thermostat.
      example: "climate.neviweb_climate_office"
    roomSetpointMax:
      description: setpoint maximum temperature to set.
      example: 25

set_setpoint_min:
  description: Set climate device room setpoint min temperature.
  fields:
    entity_id:
      description: Name(s) of neviweb device thermostat.
      example: "climate.neviweb_climate_office"
    roomSetpointMin:
      description: setpoint minimum temperature to set.
      example: 10

set_light_away_mode:
  description: Set lights devices away mode action from auto, on, off, random and none.
  fields:
    entity_id:
      description: Name(s) of neviweb light or dimmer device.
      example: "light.neviweb_light_office"
    awayMode:
      description: Select between those modes, «auto», «manualOn», «manualOff», «random» and «none».
      example: random

set_switch_away_mode:
  description: Set switchs devices away mode action from auto, on, off and none.
  fields:
    entity_id:
      description: Name(s) of neviweb switch device.
      example: "switch.neviweb_switch_office"
    awayMode:
      description: Select between those modes, «auto», «manualOn», «manualOff» and «none».
      example: auto

set_air_floor_mode:
  description: Set floor thermostat control mode; Air or Floor.
  fields:
    entity_id:
      description: Name(s) of neviweb floor thermostat.
      example: "climate.neviweb_climate_plancher_cuisine"
    airFloorMode:
      description: Set to "airByFloor" for ambiant temperature or to "floor" for floor temperature.
      example: "floor"

set_aux_cycle_length:
  description: Set low voltage thermostats auxilary cycle time in minutes.
  fields:
    entity_id:
      description: Name(s) of neviweb130 thermostat.
      example: "climate.neviweb_climate_kitchen"
    value:
      description: cycle lencht in minutes. Value are 0,5,10,15,20,25 and 30
      example: 5
